services:
  - type: web
    name: n8n-automation
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: "n8n start"
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Reuben231#"
      - key: WEBHOOK_URL
        value: "https://n8n-io-1-jotn.onrender.com"
      - key: GENERIC_TIMEZONE
        value: "Africa/Lagos"
      - key: EXECUTIONS_PROCESS
        value: "main"
